#!/bin/bash

if [ $# -eq 1 ]; then
  echo "running: ssh -t $1@$1.ssh.wpengine.net"
  ssh -t $1@$1.ssh.wpengine.net "cd sites/$1; wp core update; wp plugin update --all; wp theme update --all; exit"
fi
